### PR TITLE
Collaborate

### PR DESCRIPTION
**Pull request by Phil-Friderici**

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
@anders-larsson have reworked your spec tests a little bit. This is an suggestion only.
Added tests for stringified boold handling and variable type validation that were missing.
Removed the small fixture files.

Please don't merge, let me squash these singletons into one commit if you like it.

**Comment by anders-larsson** [comment]
Looks good :)

I've rebased my pull request against the development branch. Please rebase your commits into one and I'll merge it!

**Comment by Phil-Friderici** [comment]
rebased

**Comment by anders-larsson** [comment]
Hi,
I've cherry-picked your commit into the pull request. Closing this issue and thank you!

**Pull request closed without merging**
